version: '3'
services:
  frontend:
    image: almlrdv/react-router65-mysql-clients_app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    image: almlrdv/react-router65-mysql-clients_app-backend-dev
    restart: always
    ports:
      - '5555:5555'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: Lenuska
      MYSQL_DATABASE: books_shop
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lenuska
      MYSQL_DATABASE: books_shop
    volumes:
      - mysql_data_hub:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  mysql_data_hub:


